apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appName }}
    spec:
      # Uncomment when using aws ingress controller. Screate secret with exact matching name
      # imagePullSecret: 
      #   - name: {{ .Values.imagePullSecretName }}
      containers:
        - image: {{ .Values.imageName }}
          name: {{ .Values.appName }}-{{ randAlphaNum 5 | lower}}
          resources: {}
